/**
 * 常量统一导出
 */
export { TaskStatus, TaskStatusLabel, TaskTypeLabel } from './task';
export {
  LOGOUT_ENTRY_TEXT,
  LOGOUT_CONFIRM_TITLE,
  LOGOUT_CONFIRM_MESSAGE,
  LOGOUT_CONFIRM_CANCEL_TEXT,
  LOGOUT_CONFIRM_OK_TEXT,
} from './auth';
export {
  CATEGORY_PICKER_TITLE,
  CATEGORY_DIALOG_INTRO,
  CATEGORY_DIALOG_HINT,
  CATEGORY_SKIP_TEXT,
  CATEGORY_SAVE_TEXT,
  CATEGORY_SAVING_TEXT,
  CATEGORY_TOP_PLACEHOLDER,
  CATEGORY_SUB_PLACEHOLDER,
  CATEGORY_COUNT_ERROR_TEXT,
} from './category';
export {
  JD_MERCHANT_ID_LABEL,
  SHOP_NAME_LABEL,
  JD_MERCHANT_ID_PLACEHOLDER,
  SHOP_NAME_PLACEHOLDER,
  JD_MERCHANT_ID_INVALID_TEXT,
  SHOP_NAME_INVALID_TEXT,
  JD_MERCHANT_ID_MAX_LENGTH,
  SHOP_NAME_MAX_LENGTH,
} from './merchant';
