"""ORM 模型包(按实际库列名映射,见角色卡列名策略)。

迁移期:snake_case 表直接映射;camelCase 表(admin_account/first_level_task/
second_level_task/merchant_task_progress)按实际列名映射。切换后再统一 snake_case。
"""
from app.db.base import Base
from app.db.models import (
    admin_account,
    admin_ai_config_audit,
    ai_analysis_log,
    ai_entry_config,
    captcha_daily_counter,
    category,
    category_requirement,
    event_log,
    feedback,
    fee_config,
    fee_brand_override,
    feishu_notification,
    first_level_task,
    internal_notify_log,
    merchant,
    merchant_binding_group,
    merchant_binding_member,
    merchant_category,
    merchant_login_code,
    merchant_stage_progress,
    merchant_task_progress,
    second_level_task,
    shop_health_score,
    shop_product_count,
    shop_product_data,
    shop_star_data,
    shop_trade_data,
    shop_traffic_data,
    stage_config,
    trademark_registry,
)

# 导出契约:与上面的 import 列表一一对应(补齐原缺失的 7 个模型模块,消除两份不一致的清单)。
__all__ = [
    "Base",
    "admin_account",
    "admin_ai_config_audit",
    "ai_analysis_log",
    "ai_entry_config",
    "captcha_daily_counter",
    "category",
    "category_requirement",
    "event_log",
    "feedback",
    "fee_config",
    "fee_brand_override",
    "feishu_notification",
    "first_level_task",
    "internal_notify_log",
    "merchant",
    "merchant_binding_group",
    "merchant_binding_member",
    "merchant_category",
    "merchant_login_code",
    "merchant_stage_progress",
    "merchant_task_progress",
    "second_level_task",
    "shop_health_score",
    "shop_product_count",
    "shop_product_data",
    "shop_star_data",
    "shop_trade_data",
    "shop_traffic_data",
    "stage_config",
    "trademark_registry",
]